# Generated by Django 2.0 on 2019-01-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageIncoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_envelope_sender', models.EmailField(max_length=70)),
                ('msg_envelope_recipient', models.EmailField(max_length=70)),
                ('msg_from_email', models.CharField(max_length=70)),
                ('msg_from_email_addr_spec', models.EmailField(blank=True, max_length=100, null=True)),
                ('msg_from_email_display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_from_email_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_from_email_username', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_date', models.DateTimeField(blank=True, null=True)),
                ('msg_text', models.TextField(blank=True, null=True)),
                ('msg_html', models.TextField(blank=True, null=True)),
                ('event_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_timestamp', models.DateTimeField(blank=True, null=True)),
                ('event_esp_event', models.CharField(blank=True, max_length=100, null=True)),
                ('forward_to', models.EmailField(blank=True, max_length=70, null=True)),
                ('forwarded', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='switchboard_operator.Attachment')),
            ],
            options={
                'ordering': ['-msg_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageOutgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_envelope_sender', models.EmailField(max_length=70)),
                ('msg_envelope_recipient', models.EmailField(max_length=70)),
                ('msg_from_email', models.CharField(max_length=70)),
                ('msg_from_email_addr_spec', models.EmailField(blank=True, max_length=100, null=True)),
                ('msg_from_email_display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_from_email_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_from_email_username', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('msg_date', models.DateTimeField(blank=True, null=True)),
                ('msg_text', models.TextField(blank=True, null=True)),
                ('msg_html', models.TextField(blank=True, null=True)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('attachments', models.ManyToManyField(blank=True, to='switchboard_operator.Attachment')),
            ],
            options={
                'ordering': ['-msg_date'],
                'abstract': False,
            },
        ),
    ]
